"""Slack poster for the SRE agent.

Uses a bot token (chat.postMessage) with Block Kit formatting so RCAs
render as structured messages instead of plain text walls.
"""

from __future__ import annotations

import logging
import os
from typing import Any

import requests

log = logging.getLogger(__name__)

SLACK_API = "https://slack.com/api/chat.postMessage"
TIMEOUT_S = 10


class SlackError(RuntimeError):
    pass


class Slack:
    def __init__(self, token: str | None = None, channel: str | None = None) -> None:
        self.token = token or os.environ.get("SLACK_BOT_TOKEN")
        self.channel = channel or os.environ.get("SLACK_CHANNEL_ID")
        if not self.token or not self.channel:
            raise SlackError(
                "SLACK_BOT_TOKEN and SLACK_CHANNEL_ID must be set "
                "(env vars or constructor args)."
            )

    def post_rca(
        self,
        *,
        title: str,
        summary: str,
        rca_body: str,
        fields: dict[str, str] | None = None,
        thread_ts: str | None = None,
    ) -> str:
        """Post an RCA message. Returns the message ts (usable as thread_ts).

        `fields` renders as a compact key/value grid at the top (namespace,
        pod, container, severity, etc.). `rca_body` is the LLM's analysis —
        posted as Markdown.
        """
        blocks: list[dict[str, Any]] = [
            {
                "type": "header",
                "text": {"type": "plain_text", "text": title[:150], "emoji": True},
            },
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": f"*{summary}*"},
            },
        ]

        if fields:
            # Slack allows up to 10 field entries in a section.
            field_items = [
                {"type": "mrkdwn", "text": f"*{k}*\n`{v}`"}
                for k, v in list(fields.items())[:10]
            ]
            blocks.append({"type": "section", "fields": field_items})

        blocks.append({"type": "divider"})

        # Slack section text has a 3000-char limit; chunk if needed.
        for chunk in _chunk_text(rca_body, 2900):
            blocks.append(
                {"type": "section", "text": {"type": "mrkdwn", "text": chunk}}
            )

        payload: dict[str, Any] = {
            "channel": self.channel,
            "text": summary,   # fallback for notifications
            "blocks": blocks,
        }
        if thread_ts:
            payload["thread_ts"] = thread_ts

        return self._post(payload)

    def post_text(self, text: str, thread_ts: str | None = None) -> str:
        """Plain-text post; used for the initial 'investigating…' ack."""
        payload: dict[str, Any] = {"channel": self.channel, "text": text}
        if thread_ts:
            payload["thread_ts"] = thread_ts
        return self._post(payload)

    def _post(self, payload: dict[str, Any]) -> str:
        r = requests.post(
            SLACK_API,
            headers={
                "Authorization": f"Bearer {self.token}",
                "Content-Type": "application/json; charset=utf-8",
            },
            json=payload,
            timeout=TIMEOUT_S,
        )
        r.raise_for_status()
        body = r.json()
        if not body.get("ok"):
            raise SlackError(f"Slack API error: {body.get('error')} | full: {body}")
        return body["ts"]


def _chunk_text(text: str, limit: int) -> list[str]:
    """Split on line boundaries where possible; hard-cut only if a single line is too long."""
    if len(text) <= limit:
        return [text]
    out, buf = [], ""
    for line in text.splitlines(keepends=True):
        if len(line) > limit:
            # hard cut
            if buf:
                out.append(buf); buf = ""
            for i in range(0, len(line), limit):
                out.append(line[i : i + limit])
            continue
        if len(buf) + len(line) > limit:
            out.append(buf); buf = line
        else:
            buf += line
    if buf:
        out.append(buf)
    return out


# ---- CLI for manual testing ----
if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")

    slack = Slack()
    ts = slack.post_rca(
        title="🚨 PodCrashLooping — helloworld/helloworld-deployment-xxx",
        summary="Container is restarting repeatedly (CrashLoopBackOff)",
        fields={
            "Namespace": "helloworld",
            "Pod": "helloworld-deployment-85dfb4cf8f-vxn9l",
            "Container": "helloworld-container",
            "Severity": "critical",
            "Restarts": "108",
        },
        rca_body=(
            "*Root cause (stub)*\n"
            "This is a test message from the SRE agent. Real RCA will be "
            "generated by Claude in the next step.\n\n"
            "*Suggested fix*\n"
            "• Check that the container's readiness/liveness probe ports "
            "match the port the app actually listens on."
        ),
    )
    print(f"Posted message ts={ts}")
